### ISSUE TITLE
Tabla ProductoProveedor, Modelo y Controlador ( 20 ptos) 

### ISSUE THREAD

**Issue by carlospiedrab** [carlospiedrab/Integracion#14]
Se necesita crear una nueva tabla en la Base de datos llamada ProductoProveedor la cual tendrá las siguientes columnas:

ProductoProveedorId int Not null (PK)
ProveedorId int Not Null (FK Tabla Proveedor)
ProductoId  int Not Null (FK Tabla Producto)

* El script de la tabla se debe agregar en el proyecto de Integracion.
* Se creará el Modelo ProductoProveedor.cs en el Proyecto Models/Entidades.
* Se agregará el DbSet de ProductoProveedor en el DbContext
* Se creará un nuevo Controlador ProductoProveedorController el cual tendrá los endpoints de Crear, Eliminar y Consultar.
* Se crearan DTOs para la presentacion de los datos, por ejemplo al consultar los registros estos deberan mostrar el Nombre Del Producto, Nombre Categoria, Nombre Marca y Nombre Proveedor.

**Comment by mdalex2** [comment]
El nuevo commit contiene corrección en el nombre de la tabla en el dbset está en plural y no lo reconocía porque el modelo está en singular se agregó Table("ProductoProveedor") para evitar este conflicto a nivel de modelo.
