### ISSUE TITLE
Estado en Categoria y Marca (20 ptos)

### ISSUE THREAD

**Issue by carlospiedrab** [carlospiedrab/Integracion#16]
Actualmente las tablas y Modelos Categoria y Marca tienen las siguientes columnas y propiedades:
Id
Nombre

Se necesita agregar una nueva columna en las tablas de la Base de datos llamada Estado ([Estado] [bit] NOT NULL) y que se vea reflejada en los Modelos Categoria.cs y Marca.cs (bool True/False). Los nuevos productos a crearse solo se podrán crear con Categorias y Marcas Activas.

* Se alterará las tablas Categoria y Marca agregando una nueva columna Estado.
* El script del alter de las tablas se debe de agregar al proyecto como un archivo .sql
* Se agregará la nueva propiedad Estado a la clase Categoria.cs y Marca.cs
* Se modificará el endpoint Post en el controlador ProductoController que permitirá crear Productos solo de Categorias y Marcas Activas (Estado === True). Esto debe de ser una validación antes de grabar. Si la Categoria o Marca enviada en el body request no esta activa entonces generar un Bad Request que indique que no se pudo crear el Producto.
* Los endpoints de consulta de ProductoController solo podrán ser consultados por usuarios con el Rol Admin y Vendedor y los endpoints de Post, Update y Delete por usuarios con el rol Admin.

**Comment by oscar1912** [comment]
Fueron completados los cambios y se envio el PR para aprobacion
