### ISSUE TITLE
Agregar Tabla, Modelo y Controlador Compañia (20 ptos)

### ISSUE THREAD

**Issue by carlospiedrab** [carlospiedrab/Integracion#26]
Para los futuros requerimientos de Facturación de Productos se necesita tener los datos de la Compañía.

Se debe de crear en la Base de datos la tabla Compania con las siguientes columnas:
CompaniaId int Not Null (PK),
Nombre nvarchar(100) Not Null,
Descripcion nvarchar(100) Not Null,
Direccion nvarchar(100) Not Null,
Telefono nvarchar(40) Not Null,
Email nvarchar(100) Not Null,,
Estado bit Not Null

* El script de la creación de la tabla se debe agregar en el proyecto de Integración en el directorio Scripts
* Se necesita crear un Modelo (Compania.cs) en nuestro proyecto Integracion Models/Entidades que este mapeada con esta nueva tabla Compania, agregarla al DbContext para poder utilizar las operaciones de Entity Framework y crear un nuevo controlador CompaniaController que tenga los diferentes endpoints que permitan Crear, Actualizar, Consultar y Eliminar Companias.

* Se pueden crear Dtos para la presentación e ingreso de los datos.

**Comment by mdalex2** [comment]
En el controller creo que sería CRUD de compañía no de proveedores ?

**Comment by carlospiedrab** [comment]
Tienes razón lo acabo de editar.
