### ISSUE TITLE
Ordenes de Compra por Proveedor ( 30 ptos )

### ISSUE THREAD

**Issue by carlospiedrab** [carlospiedrab/Integracion#29]
Se necesita incluir en el proyecto la creación de Ordenes de Compra por Proveedor. Es decir que cada vez que se desee aumentar el Inventario de Productos, este proceso pase por una Orden de Compra de Proveedores. Para llevar a cabo este proceso se necesita de las siguientes tablas:

OrdenCompra
--------------
OrdenCompraId  int Not Null ( Pk )
ProveedorId    int Not Null ( FK Tabla Proveedor )
BodegaId int Not Null ( FK Tabla Bodega )
FechaIngreso   datetime Not Null
UsuarioId      string Not Null (FK Tabla AspNetUsers )
TotalOrden     decimal Not Null (Suma de Subtotales del detalle Costo Producto * Cantidad)

OrdenCompraDetalle
---------------
OrdenCompraDetalleId  int Not Null ( Pk )
OrdenCompraId         int Not Null ( FK Tabla Orden Compra )
ProductoId            int Not Null ( FK Tabla Producto )
Cantidad              int Not Null
Costo                 decimal Not Null ( Costo Actual del Producto )
Subtotal              decimal Not Null ( Costo * Cantidad )

* En el proyecto Integracion se deben de agregar los dos nuevos Modelos en Models/Entidades mapeados con las nuevas tablas.
* Se debe agregar un Dto que tenga la Información de la Cabecera y Detalle de la Orden de Compra.
* Se debe agregar al DbContext los nuevos modelos para poder usar los métodos de EntityFramework.
* Se debe agregar el controlador OrdenCompraController.
* El controlador OrdenCompraController debe de tener 2 endpoints:
  Post .- Que permita Ingresar nuevas Ordenes de Compra por Proveedor. Se debe afectar el inventario(Tabla BodegaProducto) y se debe registrar el kardex a través del servicio KardexService.
  Get by OrdenId .- Consulta de Ordenes de Compra por Id.
* Validaciones:
  Los Productos a incluir en el Detalle de la Orden de Compra deben de ser del Proveedor de la OC. Verificar la tabla ProductoProveedor.
Las cantidades no pueden ser cantidades negativas.

**Comment by ChristianV86** [comment]
Saludos. Ingeniero @carlospiedrab una pregunta. Con respecto al punto 'Validaciones'. Según lo que entiendo no es la Fk de la tabla 'Proveedor' la que se debe incluir en la tabla 'OrdenCompraDetalle', sino la Fk de la tabla 'ProductoProveedor'. Si es así o estoy equivocado. Estaré atento para continuar. Muchas gracias.

**Comment by carlospiedrab** [comment]
Saludos Christian. A lo que se refiere el requerimiento es que la validación debe verificar que el productoId que se vaya a agregar en el detalle de la Orden de compra pertenezca al Proveedor de la Cabecera de la Orden y ese dato lo tienes en la tabla o Modelo ProductoProveedor.
