### ISSUE TITLE
Agregar Tabla, Modelo y Controlador Cliente (20 ptos)

### ISSUE THREAD

**Issue by carlospiedrab** [carlospiedrab/Integracion#32]
Se necesita crear en la Base de datos una nueva tabla de Clientes, las columnas serán las siguientes:
ClienteId    int  Not Null ( PK ),
Nombres      nvarchar(100) Not Null,
Apellidos    nvarchar(100) Not Null,
Direccion    nvarchar(100) Not Null,
Telefono     nvarchar(60) Not Null,
Email        nvarchar(100) Not Null,
Estado       bit Not Null

Se necesita crear un Modelo (Cliente.cs) en nuestro proyecto Integracion que este mapeada con esta nueva tabla Provedor  models/entidades, agregarla al DbContext para poder utilizar las operaciones de Entity Framework y crear un nuevo controlador ClienteController que tenga los diferentes endpoints que permitan Crear, Actualizar, Consultar y Eliminar Clientes.

Se pueden crear Dtos para la presentación e ingreso de los datos.

**Comment by mdalex2** [comment]
En este ejercicio debe estar mapeada a Proveedor ? es decir deberia ser relacion de un cliente muchos proveedores  y a su vez, modificar todo lo relacionado con proveedor para que permita esta nueva relación con los clientes?

**Comment by carlospiedrab** [comment]
Saludos. Realmente el objetivo de Clientes es para la Facturación de los productos. Vamos a tener la parte de facturación y es ahí en donde vamos a necesitar el Id del Cliente.
