### ISSUE TITLE
Cumplimiento normativo

### ISSUE THREAD

**Issue by davidds26** [carlospiedrab/Integracion#35]
En entornos donde se manejan datos sensibles o se deben cumplir normativas estrictas, la encriptación de la cadena de conexión puede ser un requisito legal o regulatorio para proteger la privacidad de los datos. 

La cadena de conexión puede contener información sensible como nombres de usuario, contraseñas y detalles de la ubicación del servidor de base de datos,  Este Issues requiere de crear el mecanismo de poder encriptar esos datos sensible que se encuentran en el proyecto.

Issues Pendiente de aprobación por el TeachLeader (Carlos Piedra)

**Comment by carlospiedrab** [comment]
Puedes trabajar en este Issue sin ningun problema.

**Comment by davidds26** [comment]
listo
