### ISSUE TITLE
Perfil de Usuario por Id (10 pts)

### ISSUE THREAD

**Issue by carlospiedrab** [carlospiedrab/Integracion#9]
Actualmente en el controlador de usuario (AccountController) se encuentran los siguientes endpoints:
/api/Account   -- Listado de Usuarios
/api/Account/Registro  -- Registro de nuevos usuarios
/api/Account/Login  -- Login de usuarios existentes
/api/Account/ListadoRoles  -- Listado de los Roles Existentes

Se necesita un nuevo endpoint /api/Account/Perfil el cual recibira como parámetro de ruta el Id del usuario y retornará en el response los datos del usuario. La ruta completa del endpoint será: 
/api/Account/id

Se usará el dto UsuarioDto para presentar los datos del usuario y se usará el ApiResponse para el response del endpoint, se puede ver el ejemplo en el endpoint /api/Account.

**Comment by mdalex2** [comment]
@carlospiedrab en este requerimiento cuando se pide obtener por Id del usuario se refiere al GUID? ya que la tabla contiene es un GUID estilo "2d9c5e03-d1c2-4db1-9e6c-d4d2125948de"

**Comment by carlospiedrab** [comment]
Es asi, el id es un GUID la idea es filtrar por ese Id.
